name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker images
      run: |
        docker build -t murali54321/frontend:latest ./frontend
        docker build -t murali54321/backend:latest ./backend

    - name: Push Docker images
      run: |
        docker push murali54321/frontend:latest
        docker push murali54321/backend:latest

    - name: Deploy to Kubernetes
      uses: kubernetes-actions/kubectl@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        args: apply -f kubernetes
